### ISSUE TITLE
Sunset and sunrise

### ISSUE THREAD

**Issue by luis-sanmiguel** [xoseperez/espurna#2127] opened 2020-01-27 19:05 UTC
Hi,

I have always believed that it would be interesting to add a functionality that allowed taking into account the sunrise and sunset times to delay or advance certain actions. For example, instead of turning on a light always at the same time, which may be too late in winter and too soon in summer, to be able to keep in mind as I say the hours of sunrise and sunset. This way you could program the light to come on 1 hour after sunset and 1 hour before sunrise.

What I do right now is to consult this data via the sunrise-sunset.org API and based on them I plan the tasks and actions I want.

**Comment by mcspr** [comment] 2020-01-29 16:29
See https://github.com/xoseperez/espurna/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sunrise 
There was an experimental sensor to send such data. It needs some cleanup though.
https://github.com/poulch74/espurna/blob/espurna-poulch74/code/espurna/sunrise.ino
https://github.com/poulch74/espurna/blob/espurna-poulch74/code/espurna/sensors/SunriseSensor.h
https://github.com/poulch74/espurna/blob/espurna-poulch74/code/espurna/libs/Sunrise.h

Scheduling part can be achieved through rpn?
https://github.com/xoseperez/espurna/wiki/RPN-Rules#rule-execution
Sensor code above hijacks analog sensor as magnitude, but that can be reworked. For example, sensor will return 0 for night and 1 for day.
*edit:* as for -1 or +1 hour offsets, another option is to report two values as seconds until either sunrise or sunset.

Duplicate of #1263 ([for some reason github does not pick this up...](https://help.github.com/en/github/managing-your-work-on-github/about-duplicate-issues-and-pull-requests))

**Closed as completed by mcspr** 2020-01-29 16:29 UTC
Labels: duplicate, enhancement

**Comment by luis-sanmiguel** [comment] 2020-02-05 22:41
Thank you sir.
