### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by s0ftcorn** [xoseperez/espurna#2198] opened 2020-03-28 19:52 UTC
When building espurna with latest platformio in vscode i get the following error while installing dependencies:
Cloning into 'C:\Users\Arno\Nextcloud\gefrickel\3D\Firmware\espurna\code\.pio\libdeps\nodemcu-lolin\_tmp_installing-eznre3f3-package'...
warning: unable to unlink 'travis': Directory not empty
fatal: cannot create directory at 'travis': Directory not empty

Since i did not change anything, i think this is a bug in the code not caused by me.

**Comment by mcspr** [comment] 2020-03-30 11:34
Duplicate of #2006
(at least what it seems like)

**Closed as completed by mcspr** 2020-03-30 11:34 UTC
