### ISSUE TITLE
Alexa and Domoticz malfunction

### ISSUE THREAD

**Issue by Carmelo66** [xoseperez/espurna#2036] opened 2019-12-02 15:17 UTC
Espurna 1.14.0 Alexa malfunction and domoticz bad, downgrade to 1.13.5 Domoticz is ok. Alexa malfunction. First with this version everything was ok, after downgrade no

**Comment by Carmelo66** [comment] 2019-12-02 18:40
First the Alexa devices saw them as Wemo plug and they worked well, now they see them as Royal Philips Electronics smart devices and they are no longer working, even making the downgrade from 1.14.0 to 1.13.5 they always remain Royal Philips and not working with Alexa, while returning to work with Domoticz.

**Comment by mcspr** [comment] 2019-12-03 08:44
Duplicate of https://github.com/xoseperez/espurna/issues/2034 and https://github.com/xoseperez/espurna/issues/1904

**Closed by mcspr** 2019-12-03 08:44 UTC
