### ISSUE TITLE
Brigness and color change on light doesn't work with Alexa

### ISSUE THREAD

**Issue by hamed-ta** [xoseperez/espurna#2512] opened 2022-05-02 19:14 UTC
I have one RGBWW light device with Espurna. when I ask alexa to search for devices it finds 5 different light bulbs, it seems one for each color! but only cold white and warm white work as a switch and the brightness and color changes doesn't work at all. what is the problem?

![Screen Shot 2022-05-02 at 23 39 23](https://user-images.githubusercontent.com/9883945/166310254-f5340cc1-3dc3-4f52-994b-e7781ab017f2.png)
![IMG_0244](https://user-images.githubusercontent.com/9883945/166310366-53ad0009-7946-474b-8cf6-eceff0ded247.jpeg)

**Comment by mcspr** [comment] 2022-05-05 17:11
It is the way it is implemented in the fauxmoESP.
Also, duplicate of https://github.com/xoseperez/espurna/issues/1636

I am not using Echo, and (still) don't really understand it's inner workings, so can't really help there. You can check out the proposed colour control branch at https://github.com/vintlabs/fauxmoESP/pull/180 (https://github.com/vintlabs/fauxmoESP/tree/Colour) which seems to do what you want.

**Closed as completed by mcspr** 2022-05-05 17:11 UTC

**Comment by hamed-ta** [comment] 2022-05-09 06:16
I will try to use Espalexa which seems more promising.
