### ISSUE TITLE
Sonoff DUAL R2 - when power outage, switch #1 went to ON?

### ISSUE THREAD

**Issue by lesleypersyn** [xoseperez/espurna#1593] opened 2019-02-28 14:34 UTC
The 2 switches are configured to "Zero or one switches active"
Boot mode = Always OFF
Pulse mode = Normally Off
Pulse time(s) = 30
MQTT group = empty
MQQT group sync = Same
On MQTT Disconnect = Don't change

Version 1.13.3 precompiled OTA

When i remove the power from the DUAL R2 and add power the Switch #1 (not #0) goes to ON. On that moment there is no WIFI and this wasn't the last selected option (last action was Switch #0 to On)
I cannot find why it have this behavior.
thanks!

**Comment by mcspr** [comment] 2019-02-28 18:31
Duplicate of #1254 

Please update, new version has a fix

**Closed by mcspr** 2019-02-28 18:31 UTC
Labels: duplicate
