### ISSUE TITLE
PermissionError: [WinError 5] 拒绝访问   Compile Error

### ISSUE THREAD

**Issue by adsl865** [xoseperez/espurna#2351] opened 2020-09-12 07:17 UTC
Processing wemos-d1mini (board: d1_mini; platform: espressif8266@1.5.0; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (1.5.0) > WEMOS D1 mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 1.20300.1 (2.3.0)
 - tool-esptool 1.409.0 (4.9)
 - toolchain-xtensa 1.40802.0 (4.8.2)
Converting espurna.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing git+https://github.com/me-no-dev/ESPAsyncTCP#7e9ed22
git version 2.28.0.windows.1
Cloning into 'C:\Users\FSY-WIN10-5W\.platformio\.cache\tmp\pkg-installing-x5pnled5'...
HEAD is now at 7e9ed22 Bump version in Arduino and fix compilation erros
PermissionError: [WinError 5] 拒绝访问。: 'C:\\Users\\FSY-WIN10-5W\\.platformio\\.cache\\tmp\\pkg-installing-x5pnled5\\.git\\objects\\pack\\pack-c06bfa45e86338612aa04d98e684bc449d91bf10.idx':
  File "C:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 169:
    env.SConscript("$BUILD_SCRIPT")
  File "C:\Users\FSY-WIN10-5W\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "C:\Users\FSY-WIN10-5W\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Script\SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "C:\users\fsy-win10-5w\.platformio\platforms\espressif8266@1.5.0\builder\main.py", line 375:
    target_elf = env.BuildProgram()
  File "C:\Users\FSY-WIN10-5W\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 62:
    env.ProcessProjectDeps()
  File "C:\Users\FSY-WIN10-5W\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 140:
    project_lib_builder = env.ConfigureProjectLibBuilder()
  File "C:\Users\FSY-WIN10-5W\.platformio\packages\tool-scons\scons-local-4.0.1\SCons\Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "C:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py", line 1062:
    project.install_dependencies()
  File "C:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\builder\tools\piolib.py", line 898:
    lm.install(spec)
  File "c:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 49:
    spec, silent=silent, skip_dependencies=skip_dependencies, force=force
  File "c:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\package\manager\library.py", line 86:
    force=force,
  File "c:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 97:
    pkg = self.install_from_url(spec.url, spec, silent=silent)
  File "c:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 152:
    return self._install_tmp_pkg(pkg_item)
  File "c:\users\fsy-win10-5w\.platformio\penv\lib\site-packages\platformio\package\manager\_install.py", line 241:
    shutil.move(tmp_pkg.path, dst_pkg.path)
  File "C:\Users\FSY-WIN10-5W\.platformio\python3\lib\shutil.py", line 578:
    rmtree(src)
  File "C:\Users\FSY-WIN10-5W\.platformio\python3\lib\shutil.py", line 516:
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\FSY-WIN10-5W\.platformio\python3\lib\shutil.py", line 395:
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\FSY-WIN10-5W\.platformio\python3\lib\shutil.py", line 395:
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\FSY-WIN10-5W\.platformio\python3\lib\shutil.py", line 395:
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\FSY-WIN10-5W\.platformio\python3\lib\shutil.py", line 400:
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\FSY-WIN10-5W\.platformio\python3\lib\shutil.py", line 398:
    os.unlink(fullname)
================================================================================================= [FAILED] Took 17.10 seconds =================================================================================================

Environment    Status    Duration
-------------  --------  ------------
wemos-d1mini   FAILED    00:00:17.102

---------------------
I also tried to compile other firmware ESPEasy Tasmota 8.5 are all normal. Only ESPurna prompts errors! !

**Comment by mcspr** [comment] 2020-09-12 14:26
Duplicate of #2344 *(...4 issues below...)

Try disabling AV software.
(in case of VSCode) Try disabling `git.enabled` when building

You are not using up-to-date version, too, we no longer build with espressif8266@1.5.0

**Closed as completed by mcspr** 2020-09-12 14:26 UTC
